Added currentCourseID in message oBject and rename of functions about…
ffc91/xatkit-moodle-platform pull request #8
Opened 2019-12-12 21:24 UTC by ffc91

added currentCourseID to be received by xatkit in the messageObject

2019-12-13 02:19 UTC, nerlichman requested changes
Minor changes to variable names that I think could be helpful

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/io/MoodleIntentProvider.java
> +                        Log.info("Received sessionData: {0}\n", messageObject.getCurrentCourseAccess());
Habría que cambiar `sessionData` por `currentCourseId` no?

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/utils/MessageObject.java
> +    private String currentCourseAccess;
Wouldn't it be better if it was called `currentCourseId`? It would be clearer what data it actually stores

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/utils/MessageObject.java
> +     * The session data of the user who sent the message.
Needs update

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/utils/MessageObject.java
> +	public String getCurrentCourseAccess() {
Same as before: `getCurrentCourseId`

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/utils/MessageObject.java
> +	public void setCurrentCourseAccessID(String currentCourseAccess) {
If we change the parameter name, this would be a better name: `setCurrentCourseId`

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/utils/MoodleUtils.java
> +    String MOODLE_CHAT_SESSION_CONTEXT_KEY = "currentCourseAccess";
I'd change this to `currentCourseId`

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/io/MoodleIntentProvider.java
> +                        String currentCourseAccess = messageObject.getCurrentCourseAccess();
Same as below for the `MessageObject` class, I'd change this to `currentCourseId`

2019-12-13 02:19 UTC, nerlichman commented on runtime/src/main/java/com/xatkit/plugins/moodle/platform/io/MoodleIntentProvider.java
> +
Extra unnecessary breakline

2019-12-13 21:28 UTC, ffc91 commented
Added commit to resolve comments

2019-12-13 21:30 UTC, ffc91 reviewed
Added commit to resolve comments

2019-12-14 20:20 UTC, nerlichman approved these changes

2019-12-14 20:20 UTC, merged